mcq/urls.py
from django.urls import path, re_path
from mcq import views
# from django.contrib.auth import views as auth_views

urlpatterns =[
    
    path('',views.home_page,name='home'), #chenged
    path('home',views.home_page,name='home'),
    path('single_topic', views.single_topic, name='single_topic'),
    path('select_subjects',views.select_subject, name='select_subject'),
    # path('mcqlist', views.P_Mcq, name='P_Mcq'),
    path('subjectlist',views.select_subject, name='test_subject'),
    path('grandtest',views.GrandTest, name='grand_test'),
    path('test/<subject>/<topic>/<int:mcq_no>',views.test, name='test'),
    path('testresults', views.testresults, name='testresults'),
    # path('reportquestion/<int:pk>', views.report_question, name='report_question'),
    # path('postquestion', views.PublicMcqFormView.as_view(), name='post-question'),
    # path('postanswer', views.Post_A.as_view(), name='post-answer'),
    # path('oneliner', views.post_1liner,name='post-oneliner'),
    # path('postq', views.postq, name='postq'),
    # path('liner',views.post_1liner.as_view(), name='Post_form'),
    path('ajax/load-topic/', views.load_topic, name='ajax_load_topic'),
    # # path('posttestq', views.posttestq, name='posttestq'),
    # # path('pst', views.posttestqx, name='posttestqx'),


]

medproject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    # url(r'^select2/', include('django_select2.urls')),
    # url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('mcq.urls')),
    # path('', include('bookstore.urls')),
    # path('', include('userdata.urls')),
    # path('', include('blog.urls')),
    path('admin/', admin.site.urls),
    # path('login/', auth_views.LoginView, {'template_name':'registration/login.html'}),
    # url('^', include('django.contrib.auth.urls')),
    # path('register/', views.register, name='register'),
]

mcq/models.py
from django.db import models

# Create your models here.

from django.contrib.auth import get_user_model

User = get_user_model()

class Subject(models.Model):
    name    = models.CharField(max_length=250,unique=True)
    def __str__(self):
        return "%s" % (self.name)

class Topic(models.Model):
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    name  = models.CharField(max_length=250)


    def __str__(self):
        return "%s" % (self.name)

class Question(models.Model):
    subject    = models.ForeignKey(Subject, on_delete=models.PROTECT)
    topic       = models.ForeignKey(Topic, on_delete=models.PROTECT)
    desciption  = models.TextField(max_length=700, null=False)


    def __str__(self):
        return "%s %s %s" % (self.desciption[:100],self.topic,self.subject)

class Answers(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    option  = models.CharField(max_length=100)
    is_true  = models.BooleanField(default=False)
    explaination = models.TextField(max_length=500, null=True ,blank=True)

    def __str__(self):
        return "%s" % (self.option)

class Quiz(models.Model):
    title = models.CharField(max_length=60, blank=False)
    description = models.TextField(blank=True, help_text=("a description of the quiz"))
    subject = models.ForeignKey(Subject, null=True, blank=True, on_delete=models.PROTECT)
    topic = models.ForeignKey(Topic, null=True, blank=True, on_delete=models.PROTECT)
    quesions = models.ManyToManyField(Question)

    def __str__(self):
        return "%s" % (self.title)

class PublicMcq(models.Model):
     subject = models.ForeignKey(Subject, on_delete=models.PROTECT)
     topic    = models.ForeignKey(Topic, on_delete=models.PROTECT)
     post_date=models.DateTimeField(auto_now_add=True)
     question = models.TextField(max_length=700,null=False)
     option_a  = models.CharField(max_length=100,null=False)
     a_is_true = models.BooleanField(default=False)
     option_b = models.CharField(max_length=100, null=False)
     b_is_true = models.BooleanField(default=False)
     option_c  = models.CharField(max_length=100,null=False)
     c_is_true = models.BooleanField(default=False)
     option_d = models.CharField(max_length=100, null=False)
     d_is_true = models.BooleanField(default=False)
     
     def __str__(self):
            return "%s" % (self.question)

     

class PublicAnswers(models.Model):
    question = models.ForeignKey(PublicMcq, on_delete=models.CASCADE)
    option = models.CharField(max_length=100)
    is_true = models.BooleanField(default=False)
    explaination = models.TextField(max_length=500, null=True, blank=True)

    def __str__(self):
        return "%s" % (self.option)

mcq/forms.py
from django import forms
from dal import autocomplete
from mcq.models import Subject, Topic, Question, Answers, Quiz, PublicMcq, PublicAnswers
from django_select2.forms import Select2MultipleWidget
from django.forms import formset_factory
from django.forms.models import inlineformset_factory, modelformset_factory
from django.contrib.auth.models import User
# django_select2.forms.Select2Mixin, django.forms.widgets.Select

class QuestionForm(forms.ModelForm):
    class  Meta:
        model = Question
        fields = ('subject', 'topic', 'desciption')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['topic'].queryset = Topic.objects.none()

        if 'subject' in self.data:
            try:
                subject_id = int(self.data.get('subject'))
                self.fields['topic'].queryset = Topic.objects.filter(
                    subject_id=subject_id).order_by('name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['topic'].queryset = self.instance.subject.topic_set.order_by(
                'name')


      
class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answers
        fields = ('option', 'is_true', 'explaination')


AnswerFormSet = inlineformset_factory(Question,Answers,form=AnswerForm, extra=4, max_num=4)



class PublicMcqForm(forms.ModelForm):
    class Meta:
        model = PublicMcq
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['topic'].queryset = Topic.objects.none()
        # self.fields['city'].queryset = City.objects.none()

        if 'subject' in self.data:
            try:
                subject_id = int(self.data.get('subject'))
                self.fields['topic'].queryset = Topic.objects.filter(
                    subject_id=subject_id).order_by('name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['topic'].queryset = self.instance.subject.topic_set.order_by(
                'name')


# class OneLinerForm(forms.ModelForm):
#      class Meta:
#          model = OneLiner
#          fields= '__all__'

# trying to make view mcq_post view






# class PublicAnswersForm(forms.ModelForm):

    
#     class Meta:
#          model = PublicAnswers
#          fields = '__all__'

# class UserRegistrationForm(forms.ModelForm):
#     password = forms.CharField(widget=forms.PasswordInput(
#         attrs={'placehlder':'Enter Passowrd Here....'}))
#     confirm_password = forms.CharField(widget=forms.PasswordInput(
#         attrs={'placehlder': 'Confirm Passowrd....'}))
#     class Meta:
#         model = User
#         fields =(
#             'username',
#             'first_name',
#             'last_name',
#             'email',
#         )

#     def clean_confirm_password(self):
#         password = self.cleaned_data.get('password')
#         confirm_password = self.cleaned_data.get('confirm_password')
#         if password != confirm_password:
#             raise forms.ValidationError("Password Mismatch")
#         return confirm_password

mcq/views.py
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import CreateView,TemplateView,detail,ListView,UpdateView,DeleteView
from .models import Subject, Topic, Question,PublicMcq,PublicAnswers
from mcq.forms import PublicMcqForm, QuestionForm,AnswerForm,AnswerFormSet
from django.http import HttpResponseRedirect,HttpResponse
from django.urls import reverse_lazy,reverse
from django.contrib.auth import login,logout,authenticate
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.forms.models import inlineformset_factory, formset_factory
from mcq.models import Answers
from django.db import transaction
# Create your views here.

def home_page(request):
    return render (request,'mcq/index.html')

def select_subject(request):
    if request.method == 'GET':
        subjects = Subject.objects.all()
        return render(request, 'mcq/subject_list.html', {'subjects':subjects})

    if request.method == 'POST':
        sublist = request.POST.getlist('subject')
        # print(sublist)
        if sublist == []:
            subjects = Subject.objects.all()
            return render(request, 'mcq/subject_list.html', {'subjects': subjects, 'error':'you selected no ..'})
        subjects = Subject.objects.filter(id__in=sublist)
        return render(request, 'mcq/topic_list.html', {'subjects':subjects})
    
def load_topic(request):
    subject_id = request.GET.get('subject')
    topics = Topic.objects.filter(subject_id=subject_id).order_by('name')
    return render(request, 'mcq/topic_dropdown_list_options.html', {'topics': topics})

def GrandTest(request):
    # if request.method == 'GET':
    if request.method == 'POST':
        topics = request.POST.getlist('topic')
        topics_n_nos = {}
        for t in topics:
            topics_n_nos[t]=request.POST.get(t,'')

        qs = None
        for topic,nos in topics_n_nos.items():
            x = Topic.objects.get(id = topic)
            x = x.question_set.all()[:int(nos)]
            if qs:
                qs.union(x)
            else:
                qs = x
        hidden_q = ''
        print(qs)
        if qs is None:
            return HttpResponseRedirect(reverse('select_subject'))
        for q in qs:
            hidden_q += str(q.id)+'#'
        return render(request, 'mcq/test.html', {'questions':qs, 'hidden_q': hidden_q})


def testresults(request):
    if request.method == 'POST':
        attempted = {}
        hidden_q = request.POST.get("hidden_q", "")
        hidden_q = hidden_q.split('#')
        hidden_q = list(map(int, hidden_q[:-1]))
        for key, value in request.POST.items():
            if key != 'csrfmiddlewaretoken' and key!='hidden_q':
                attempted[key]=value

        q_list = Question.objects.filter(id__in= hidden_q)
        total_correct = 0
        for q, a in attempted.items():
            ques = Question.objects.get(pk = q)
            ans = ques.answers_set.get(pk = a)
            if ans.is_true:
                total_correct +=1

        total_attempted = len(attempted)


        context={'questions':q_list, 'attempted':attempted, 'total_attempted':total_attempted, 'total_correct':total_correct}
        return render(request, 'mcq/testresults.html', context)
    
def test(request, subject, topic, mcq_no):
    # if request.method == "GET":
    s = Subject.objects.get(id=subject)
    t = Topic.objects.get(id=topic)
    selected_questions = Question.objects.filter(subject=s, topic=t)[:mcq_no]
    hidden_q =  ''
    for q in selected_questions:
        hidden_q += str(q.id)+'#'
    return render(request, 'mcq/test1.html', {'questions':selected_questions, 'hidden_q': hidden_q})

    
def single_topic(request):
    if request.method == 'GET':
        subjects = Subject.objects.all()
        topics = Topic.objects.all()
        return render(request, 'mcq/quizetting.html', {'subjects':subjects,'topics':topics})

    if request.method == 'POST':
        subject_id = request.POST.get("subject", "")
        topic_id = request.POST.get("topic", "")
        mcq_no = request.POST.get("mcq_no", "")

        subjects = Subject.objects.all
        if subject_id != '':
            if topic_id != '':
                if int(mcq_no) >= 0 and int(mcq_no) <150:
                    return HttpResponseRedirect(reverse('test', kwargs={'subject':subject_id, 'topic':topic_id, 'mcq_no': mcq_no }))
                else:
                    pass
            else :
                topics = Subject.objects.get(id=subject_id).topic_set.all()
        else:
            topics = Topic.objects.all()
        subject_id = int(subject_id)
        return render(request, 'mcq/quizetting.html', {'subjects':subjects,'topics':topics, 'current_subject_id':subject_id})



def postq(request):
    question = Question()
    # setup a form for the parent
    question_form = QuestionForm(instance=question)


    # AnsewerInlineFormSet = inlineformset_factory(Question, Answers, extra=4)
    AnswerFormSet = inlineformset_factory(
        Question, Answers, form=AnswerForm, extra=4, max_num=4)

    if request.method == "POST":
        question_form = QuestionForm(request.POST)
        formset = AnswerFormSet(request.POST, request.FILES)

        if question_form.is_valid():
            created_question = question_form.save(commit=False)
            formset = AnswerFormSet(
                request.POST, request.FILES, instance=created_question)

            if formset.is_valid():
                created_question.save()
                formset.save()
                return redirect('post_list')
    else:
        author_form = QuestionForm(instance=question)
        formset = AnswerFormSet()

    return render(request, "mcq/testq.html", {
        "question_form": question_form,
        "formset": formset,
    })

templates/mcq/base2.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>MedWiki</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <link rel='stylesheet' href="{% static 'css/pen.css' %}">

    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet">

    {% block head_extra %}
    {% endblock %}
  </head>
  <body>
      <header>
        <div class="menu">
          <input type="checkbox" class="toggler" id="checkbox">
          <div class="hamburger">
            <div></div>
          </div>
          <div class="logo"><a href="{% url 'home' %}">MedWiki</a></div>
          <div class="navbar">
            <div class="nav-items">
              <ul>
                <li><a href="{% url 'home' %}">Home</a></li>
                <li>
                  <div class="drop1">
                    <input type="checkbox" id="drop1">
                    <label for="drop1"><a href="">Quiz<i class="material-icons">keyboard_arrow_down</i></a></label>
                    <div class="drop-menu">
                      <a href="{% url 'post-question' %}">Post Mcq</a>
                      <a href="{% url 'P_Mcq' %}">Public Mcq</a>
                      <a href="{% url 'generate_quiz' %}">Single  Topic Test</a>
                      <a href="{% url 'select_subject' %}">Multi  Topic Test</a>
                    </div>
                  </div>
                </li>
                <li>
                <div class="drop2">
                  <input type="checkbox" id="drop2">
                  <label for="drop1"><a href="">Blog<i class="material-icons">keyboard_arrow_down</i></a></label>
                  <div class="drop-menu">
                    <a href="{% url 'post_new' %}">Create Post</a>
                    <a href="{% url 'post_list' %}">Latest Post</a>
                  </div>
                </li>
                <li><a href="{% url 'book-list' %}">Library</a></li>
              </ul>
            </div>
          </div>
        </div>
      </header>
      {% block sectionheader_block %}
      {% endblock %} 
      <!-- </header>
    </section> -->
    {% block sectionheader1_block %}
    {% endblock %}

    {% block body_block %}
    {% endblock %}
  </body>
  {%block body_extra%}
  {%endblock%}
</html>

templates/mcq/baseok.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <title>test</title>
    <!-- <link rel="stylesheet" href="style.css"> -->
    <!-- <link rel='stylesheet' href="{% static 'css/bootstrap.min.css' %}"> -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"></script>
    <!-- <script src ="{% static 'js/bootstrap.min.js' %}"></script> -->
    <!-- <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script> -->

    <!-- <link rel='stylesheet' href="{% static 'css/style.css' %}"> -->
    <link rel='stylesheet' href="{% static 'css/newnav.css' %}">
    <!-- <script src ="{% static 'js/my.js' %}"></script> -->
    <!-- <script src="{% static 'js/nav.js' %}"></script> -->
    {% block head_extra %}
    {% endblock %}
  </head>
  <body>
        <nav class="navbar navbar-expand-lg my-navbar">
          <a class="navbar-brand logo" href="{% url 'home' %}">MedWiki</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            <!-- <span class="dark-blue-text"><i class="fas fa-bars fa-1x"></i></span> -->
          </button>
        
          <ul class="collapse navbar-collapse coll" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'home' %}">Home</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown">Quiz Practice</a>
                <ul class="dropdown-menu mega-menu" aria-labelledby="navbarDropdown">
                  {% comment %} <a class="dropdown-item" href="{% url 'generate_quiz' %}">Single-Topic</a> {% endcomment %}
                  <a class="dropdown-item" href="{% url 'select_subject' %}">Multi-Topic</a>
                  <!-- <div class="dropdown-divider"></div> -->
                  <!-- <a class="dropdown-item" href="#">Something else here</a> -->
                </ul>
              </li>
              <li class="nav-item">
                {% comment %} <a class="nav-link" href="{% url 'book-list' %}">Library</a> {% endcomment %}
              </li>
              <!-- <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
              </li> -->
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#"  data-toggle="dropdown">
                  Blog
                </a>
                <ul class="dropdown-menu mega-menu" aria-labelledby="navbarDropdown">
                  {% comment %} <a class="dropdown-item" href="{% url 'post_new' %}">Create Post</a> {% endcomment %}
                  <a class="dropdown-item" href="#">Create MCQ</a>
                  {% comment %} <a class="dropdown-item" href="{% url 'post_draft_list' %}">Draft</a> {% endcomment %}
                  <!-- <div class="dropdown-divider"></div> -->
                  {% comment %} <a class="dropdown-item" href="{% url 'post_list' %}">Post List</a> {% endcomment %}
                </ul>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#" tabindex="-1" aria-disabled="true">Conversation</a>
              </li>
            </ul>
            <!-- <form class="form-inline my-2 my-lg-0">
              <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form> -->
          </div>
        </nav>
    {% block sectionheader_block %}
    {% endblock %}
    {% block sectionheader1_block %}
    {% endblock %}

    {% block body_block %}
    {% endblock %}
  </body>
  {%block body_extra%}
  {%endblock%}
</html>

templates/mcq/mcqA_form.html
{% extends 'mcq/base.html' %}
{% load static %}
{% block head_extra %}
{% endblock %}



{% block body_block %}
    <form class="mcqform" name="mcqform" method="post">
           {% csrf_token %}
           {{form}}
    <input type="submit" class="btn btn btn-block" value="Submit">
    <br>
    </form>
{% endblock %}

templates/mcq/mcq_list.html
{% extends 'mcq/base.html' %}

{% block head_extra %}
<!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.10.1/bootstrap-table.min.css"> -->
<script src="//code.jquery.com/jquery.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.10.1/bootstrap-table.min.js"></script>


<style media="screen">
  .css-serial {
    counter-reset: serial-number;
    /* Set the serial number counter to 0 */
  }

  .css-serial td:first-child:before {
    counter-increment: serial-number;
    /* Increment the serial number counter */
    content: counter(serial-number);
    /* Display the counter */
  }
  .col{
    font-size: 20px;
    background-color: #ffff;
    box-shadow: 0 1.4rem 8rem rgba(0, 0, 0, 0.2);
  }
  .col li{
    margin-left: 50px;
  }
</style>
{% endblock %}

{% block body_block %}


  <br>
<div class="container">
  <div class="row justify-content-center"> 
    <div class="col">
<!-- <center><h3>List of Mcq</h3></center> -->
        {% for mcq in mcq %}
        <p>{{mcq.question}}</p>
        <ul>
         
             <li>A.{{mcq.option_a}}</li>
             <li>B.{{mcq.option_b}}</li>
             <li>C.{{mcq.option_c}}</li>
             <li>D.{{mcq.option_c}}</li>
             <li>Key:-{{mcq.answer}}</li>
          
        </ul>
        <hr>
        {%endfor%}
          
        </div>
    </div>
</div>





{% endblock %}

templates/mcq/publicmcq_form.html
{% extends 'mcq/base.html' %}
{% load static %}
{% load myfilters %}
{% block head_extra %}
{% endblock %}



{% block body_block %}
   
<!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"> -->
<style>
.container-mcq{
    align-items:center;
}
.col-center{
    margin-left: 50px;
}
.form-group h3{
    text-align: left;
}
.subject select{
    width: 80%;
    padding: 5px 35px 5px 5px;
    font-size: 16px;
    border: 1px solid black;
    height: 34px;
   border-radius: 7px;
}
.topic select{
    width: 80%;
    padding: 5px 35px 5px 5px;
    font-size: 16px;
    border: 1px solid black;
    height: 34px;
   border-radius: 7px;
}
.question textarea{
    width: 80%;
}
.option input{
    widows: 50%;
    align-items:center;
    text-align: left;
    position: flex;
    font-size: 16px;
}
</style>


<div class="container-mcq">
    <div class="row">
        <div class="col-center">
            <h2>Post MCQ</h2>
        
            <form method="post"  id="PublicMcqForm" class="myform" 
                data-topic-url="{% url 'ajax_load_topic' %}" novalidate>
                {% csrf_token %}
                <div class="form-group subject">
                    <h3>Subject</h3>
                    {{form.subject}}
                </div>
                <div class="form-group topic">
                   <h3>Topic</h3>
                    {{form.topic}}
                </div>
                <div class="form-group question">
                    <h3>Question</h3>
                    <!-- <label for="textarea">Question</label> -->
                    {{form.question}}
                </div>
                <div class="form-group option">
                    <P>Please mark the correct option (to help others) if you already know the answer, 
                        if you dont have key leave all option uncheck</P>
                    <h3>Option A</h3>
                    {{form.option_a}}
                    <input type="radio" value="{{form.a_is_true}}">
                </div>
                <div class="form-group option">
                    <h3>Option B</h3>
                    {{form.option_b}}
                    {{form.b_is_true}}
                </div>
                <div class="form-group option">
                    <h3>Option C</h3>
                    {{form.option_c}}
                    {{form.c_is_true}}
                </div>
                <div class="form-group option">
                    <h3>Option D</h3>
                    {{form.option_d}}
                    {{form.d_is_true}}
                </div>
                <div class="form-group">
                    <button name="submit" type="submit" class="btn btn-primary btn-block">Submit</button>
                </div>
                <!-- <table> -->
                    <!-- {{ form}} -->
                <!-- </table> -->
                <!-- <button type="submit">Save</button> -->
            </form>
        </div>
    </div>
</div>



<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $("#id_subject").change(function () {
        var url = $("#PublicMcqForm").attr("data-topic-url");  // get the url of the `load_cities` view
        var subjectId = $(this).val();  // get the selected country ID from the HTML input

        $.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
            data: {
                'subject': subjectId       // add the country id to the GET parameters
            },
            success: function (data) {   // `data` is the return of the `load_cities` view function
                $("#id_topic").html(data);  // replace the contents of the city input with the data that came from the server
            }
        });

    });
</script>


{% endblock %}

templates/mcq/quizetting.html
<!DOCTYPE html>
{% extends 'mcq/base.html' %}

  {% block head_extra %}
            <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"> -->

    <style type="text/css">
              .row{
                position: relative;
              }
              .btn{
                background: #6900d1 !important;
                color: #fff !important;
                margin-right: 5px;
                margin-bottom: 10px;
              }
    </style>


    {% endblock %}

{% block body_block %}
<div class="container">


        <div class="row align-items-center justify-content-center">
          <div class="col">

         
        <br>
          <form id='myform' method="POST">
            {% csrf_token %}
            <div class="form-group row align-items-center justify-content-center">
              <div class="col-8">
                <select id="subject" name="subject" class="form-control" onchange=" document.getElementById('myform').submit();">
                  <option class="ops" value='0'>Select Subject</option>
                  {% for subject in subjects %}
                  <option value={{subject.id}} {% if current_subject_id == subject.id  %}selected="selected"{% endif %}>{{subject.name}}</option>
                  {% endfor %}
                </select>
              </div>
            </div>
            <div class="form-group row align-items-center justify-content-center">

              <div class="col-8">
                <select id="topic" name="topic" class="form-control">
                  <option value=''>Select   Topic</option>
                    {% for topic in topics %}
                    <option value={{topic.id}}>{{topic.name}}</option>
                    {% endfor %}
                </select>
              </div>
            </div>
            <div class="form-group row align-items-center justify-content-center">
              <div class="col-8">
                <input id="mcq_no" name="mcq_no" type="number" value=10 class="form-control" aria-describedby="textHelpBlock">
                <span id="textHelpBlock" class="form-text text-muted">how many questions you want to try</span>
                <div class="form-group">
                  <input type="Submit" class="btn btn-block" value="Submit">
                </div>

              </div>
            </div>
          </form>
          </div>
    </div>
          <!-- <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
          <script type="text/javascript">$("#select").chained("#select1");</script> -->
{% endblock %}

templates/mcq/testresults1.html
{% extends 'mcq/base.html'%}
{%load static %}


{% block body_block %}
<style type="text/css">
.mcq li{
  list-style-type: upper-alpha;
}

</style>
<div class="container">
  <div class="row">
    <div class="col-sm">
    </div>
    <div class="col-md-8">
      <div class="mcq">
      <h1>  Your Report </h1>
      <form name="mcqform" method="post" action="/testresults">
        {% csrf_token %}
      {% for q in questions%}
        <p>{{ forloop.counter }}- {{q.desciption}}  </p>
              <ul>
              {% for a in q.answers_set.all%}
                  <!-- <li><input type="radio" name="radio" value="{{a.option}}"> {{a.option}}</li> -->
                  <li><input type="radio" name="{{q.id}}" value="{{a.id}}"> {{a.option}} {% if a.is_true %} <<{%endif%}</li>

              {%endfor%}
              </ul>
            <br>
        {%endfor%}
        <input type="submit" value="Submit" >
        </form>
      </div>
    </div>
    <div class="col-sm">
    </div>
  </div>
</div>


{% endblock %}